#!/usr/bin/env bash

RECAPCLI_DIR="$(cd "$(dirname "$(realpath \
  "${BASH_SOURCE[0]}")")" >/dev/null 2>&1 && pwd)"

progname="$(basename "$0")"

params="$(getopt -n "$progname" \
  -o h,H,d: \
  -l hidden,nohidden,date: -- "$@")" ||
  exit 1
eval set -- "$params"

while [[ $# > 0 ]]; do
  case $1 in
    -h|--hidden )
      RECAP_HIDDEN=1
      ;;
    -H|--nohidden )
      RECAP_HIDDEN=
      ;;
    -d|--date )
      date="$2" ; shift
      ;;
    -- )
      shift
      break
      ;;
  esac
  shift
done

# Assigns variable "${!var}" to the first existing file in "${paths[@]}".
read_paths_to_var() {
  var="${1?}"; shift
  paths=("$@")
  [ -n "${!var}" ] && return  # Already defined.
  for path in "${paths[@]}"; do
    [ -f "$path" ] && export "$var"="$path" && break
  done
}

# Set RECAP_SCHED_PATH in bashrc to override this.
read_paths_to_var RECAP_SCHED_PATH \
  ~/.recap/schedule.txt "$RECAPCLI_DIR/schedule.txt"

# Set RECAP_NOTES_PATH in bashrc to override this.
read_paths_to_var RECAP_NOTES_PATH \
  "notes.recap" ~/.notes.recap ~/.recap/notes.recap

while read -r sched; do
  grep "$(date -d "$date + $sched days ago" -I)" "$RECAP_NOTES_PATH" |
    { [ -n "$RECAP_HIDDEN" ] && sed 's/{[^}]*}/*/g' || cat; }
done < "$RECAP_SCHED_PATH"
